name: "Roam Research backup"

on:
  # if you are using a schedule, you can remove the push event
  # push:
  #   branches:
  #     - main
  schedule:
      # Here you can change how often your backup runs. See https://crontab.guru/examples.html
      - cron: "0 0 * * *"
  workflow_dispatch: # Allows you to run the workflow manually

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ secrets.BACKUP_REPO }}
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      -   name: Set up Python 3.12
          uses: actions/setup-python@v1
          with:
            python-version: 3.12

      -   name: Setup dependencies
          run: |
            pip install requests

      - name: Run Backup
        run: |
          #!/bin/bash
          cd /tmp
          git clone -q https://github.com/lucigo16/roam2github.git roam2github
          cd $_
          npm i --omit=dev
          npm run backup -s

          cd $GITHUB_WORKSPACE
          
          mkdir -p scripts
          cd scripts
          curl -fL https://raw.githubusercontent.com/lucigo16/roam2github-actions/main/scripts/roam_image_backup.py -o roam_image_backup.py
          curl -fL https://raw.githubusercontent.com/lucigo16/roam2github-actions/main/scripts/main.py -o main.py
          cd ..
          python scripts/main.py
        env:
          ROAM_EMAIL: ${{ secrets.ROAM_EMAIL }}
          ROAM_PASSWORD: ${{ secrets.ROAM_PASSWORD }}
          ROAM_GRAPH: ${{ secrets.ROAM_GRAPH }}
          BACKUP_EDN: true
          BACKUP_JSON: true
          BACKUP_MARKDOWN: true

      - name: Commit Changes
        uses: everruler12/git-auto-commit-action@latest
        with:
          commit_message: Automatic backup